# -*- coding: utf-8 -*-
"""CHOCOLATE_SALES_PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PTpCKY3kEzpHvFSpGLPSj85l92bEfol
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Chocolate_Sales.csv")
df

df.info()

"""# check for null values

"""

df.isnull().sum().sum()

df.isnull().sum()

"""there is 0.23 pr only null value for order date so best practice is drop the rows and order date is critical attibute."""

df = df.dropna(subset=["Order_Date"])

df['Discount_Pct'].unique()

df['Discount_Pct'].describe()

df['Discount_Pct'].skew()

"""skewness is 0.3 it is approx normal distribution so we can use mean"""

df['Discount_Pct'] = df['Discount_Pct'].fillna(df['Discount_Pct'].mean())

df['Price_per_Box'] = df.groupby('Product')['Price_per_Box'].transform(lambda x: x.fillna(x.median()))

df['Marketing_Spend'].skew()

"""skewness is more than one so it is highly skewed we can use medain"""

df["Marketing_Spend"] = df["Marketing_Spend"].fillna(df["Marketing_Spend"].median())

df.isnull().sum()

"""# check for duplicates"""

df.duplicated().sum()

# if there is duplicates in the data handle with
# df.drop_duplicates(inplace = True)

"""# check for outliers"""

df.columns

for i in df.columns:
  if(df[i].dtype != "object"):
    plt.boxplot(df[i])
    plt.title(i)
    plt.show()

df.columns

for i in df.columns:
  if(df[i].dtype != "object"):
    q1 = df[i].quantile(0.25)
    q3 = df[i].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)
    df = df[(df[i] >= lower_bound) & (df[i] <= upper_bound)]

for i in df.columns:
  if(df[i].dtype != "object"):
    plt.boxplot(df[i])
    plt.title(i)
    plt.show()

"""Note: Outliers were removed using the IQR method. Some outliers may still remain because removing extreme values changes the IQR boundaries. To avoid excessive data loss and preserve valid business observations, outlier removal was performed only once.

capping method: capping can be used to reduce the impact of outliers while preserving the dataset.

"""

df

df.info()

# Convert Date Column with error handling and drop rows with unparseable dates
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', dayfirst=True, errors='coerce')
df = df.dropna(subset=['Order_Date']) # Remove rows where date parsing failed (resulted in NaT)

# Convert Amount to Numeric
df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')

df.isnull().sum()

df['Amount'] = df.groupby('Product')['Amount'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

df.to_csv('Chocolate_Sales_Cleaned.csv', index=False)

df.isnull().sum().sum()

df.info()

from google.colab import files

files.download("Chocolate_Sales_Cleaned.csv")

"""This saves the `df` DataFrame to a file named `Chocolate_Sales_Cleaned.csv` in the current directory. The `index=False` argument prevents pandas from writing the DataFrame index as a column in the CSV file."""

df['Month'] = df['Order_Date'].dt.month_name()

month_order = ['January','February','March','April','May','June',
               'July','August','September','October','November','December']

df['Month'] = pd.Categorical(df['Month'],
                             categories=month_order,
                             ordered=True)

monthly_sales = df.groupby('Month')['Amount'].sum()

plt.figure(figsize=(8,6))
plt.plot(monthly_sales.index, monthly_sales.values,
         marker='o', linewidth=3)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales Amount")
plt.xticks(rotation=45)
plt.grid(True)

plt.show()

"""- December has the highest sales, while June records the lowest sales, indicating strong seasonal variation in chocolate demand.

- Sales show a clear recovery from July to December, with strong growth in October, November, and December.

- The business should prepare higher inventory and marketing campaigns before the year-end period, while investigating the reasons behind the June–July slowdown.
"""

top_products = df.groupby('Product')['Amount'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(8,6))
top_products.plot(kind='bar')

plt.title("Top 10 Selling Products")
plt.xlabel("Product")
plt.ylabel("Sales Amount")
plt.xticks(rotation=45)
plt.grid(axis='y')

plt.show()

"""- 70% Dark Bar is the clear best-selling product.

- Truffle Gift Box and Mixed Assortment Box are the next strongest product, which indicate contribute significantly to revenue.

- The company should prioritize inventory and marketing for the top-performing products while reviewing whether lower-performing products should be promoted, repositioned, or reduced.
"""

contry_sales = df.groupby('Country')['Amount'].sum().sort_values(ascending=False)
plt.figure(figsize=(8,6))
contry_sales.plot(kind='bar')
plt.title("Sales by Country")
plt.xlabel("Country")
plt.ylabel("Sales Amount")
plt.grid(axis='y')
plt.show()

"""- Australia is the highest-revenue market, followed by Brazil.

- India and Japan contribute considerably less sales than Australia and Brazil, indicating potential opportunities for market expansion.

- The company could increase marketing and distribution efforts in India and Japan while maintaining strong customer retention strategies in Australia and Brazil.
"""

channel_sales = df.groupby('Channel')['Amount'].sum()

plt.figure(figsize=(7,5))
channel_sales.plot(kind='pie')

plt.title("Sales by Channel")
plt.xlabel("Channel")
plt.ylabel("Sales Amount")

plt.show()

"""- Retail is the dominant sales channel, contributing the largest share of total sales.
- Wholesale is the second-largest channel, showing that bulk/business customers are also an important revenue source.
- Online has the smallest contribution, suggesting an opportunity to strengthen e-commerce through digital marketing, online promotions, and better customer acquisition.
"""

top_salesperson = df.groupby('Salesperson')['Amount'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
top_salesperson.plot(kind='barh')

plt.title("Top 10 Salespersons")
plt.xlabel("Sales Amount")

plt.show()

"""- Arjun Mehta is the top-performing salesperson by a very large margin, significantly outperforming the other salespeople.
- Priya Sharma and Emily Clarke are the next strongest performers, but there is still a huge gap between them and Arjun.
"""

plt.figure(figsize=(8,6))

plt.scatter(df['Marketing_Spend'], df['Amount'])

plt.title("Marketing Spend vs Sales")
plt.xlabel("Marketing Spend")
plt.ylabel("Sales Amount")
plt.grid(True)

plt.show()

"""- The scatter plot shows a positive relationship between marketing spend and sales, meaning higher marketing investment is generally associated with higher sales.

- The correlation shown in your heatmap is approximately 0.36, indicating a moderate positive relationship. The company should measure marketing ROI rather than simply increasing marketing expenditure
"""

plt.figure(figsize=(8,6))

plt.scatter(df['Discount_Pct'], df['Amount'])

plt.title("Discount vs Sales")
plt.xlabel("Discount (%)")
plt.ylabel("Sales Amount")
plt.grid(True)

plt.show()

"""- The points show no strong visible relationship between discount percentage and sales, meaning increasing discounts does not consistently result in higher sales.

- Your correlation heatmap shows a correlation of approximately 0.02 between Discount_Pct and Amount, which is extremely weak.

- This suggests the company should avoid relying heavily on discounts to increase revenue and instead focus on product positioning, distribution, marketing, and customer targeting.
"""

plt.figure(figsize=(8,5))

plt.hist(df['Price_per_Box'], bins=20)

plt.title("Price per Box Distribution")
plt.xlabel("Price per Box")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

"""- Most boxes have a price concentrated around approximately 2.8–3.5, indicating that this is the company's primary pricing range.

- The distribution is right-skewed, with some products having considerably higher prices.

- The company can use this information to maintain a core affordable price range
"""

import seaborn as sns

plt.figure(figsize=(8,6))

sns.heatmap(df[['Discount_Pct','Price_per_Box','Marketing_Spend',
                'Boxes_Shipped','Amount']].corr(),
            annot=True,
            cmap='coolwarm')

plt.title("Correlation Heatmap")

plt.show()

"""- Boxes Shipped and Amount have a very strong positive correlation of 0.89, indicating that the number of boxes sold is the primary driver of sales revenue.

- Marketing Spend and Amount have a moderate positive correlation of 0.36, suggesting marketing contributes to sales but is not the only factor driving revenue.

- Discount_Pct and Amount have almost no correlation (0.02), indicating that discounts have very little linear relationship with sales amount in this dataset.
"""